Groovy25 (#991)
* AbstractToolTest: assert stderr first and don't interpret the empty string as "everything matches"

We assert stderr first because this shows unexpected exceptions to ease debug.
We match the empty string exactly because most tests should not write anything
to stderr. If they do, it's probably an unexpected exception that we want to
display.

Without these two changes, it's very hard to debug these tests.

Signed-off-by: Jon Harper <jon.harper87@gmail.com>

* Replace groovy-all with specific groovy module dependencies

Signed-off-by: Jon Harper <jon.harper87@gmail.com>

* Update to groovy 2.5 to use new groovy META-INF/groovy folder to allow packaging as a java9 JPMS module

Fixes the following error:
$ java --module-path powsybl-iidm-api.jar Foo
Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for powsybl-iidm-api.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Provider class moduleName = powsybl-iidm-module not in module

or the equivalent :
$ jar --file=powsybl-iidm-api.jar --describe-module
Unable to derive module descriptor for: /home/harperjon/.m2/repository/com/powsybl/powsybl-iidm-api/2.6.0/powsybl-iidm-api-2.6.0.jar
Provider class moduleName = powsybl-iidm-module not in module

Signed-off-by: Jon Harper <jon.harper87@gmail.com>