Update to groovy 2.5 to use new groovy META-INF/groovy folder to allow packaging as a java9 JPMS module
Fixes the following error:
$ java --module-path powsybl-iidm-api.jar Foo
Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for powsybl-iidm-api.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Provider class moduleName = powsybl-iidm-module not in module

or the equivalent :
$ jar --file=powsybl-iidm-api.jar --describe-module
Unable to derive module descriptor for: /home/harperjon/.m2/repository/com/powsybl/powsybl-iidm-api/2.6.0/powsybl-iidm-api-2.6.0.jar
Provider class moduleName = powsybl-iidm-module not in module

Signed-off-by: Jon Harper <jon.harper87@gmail.com>