Add logback-core explicit dependency in dependencyManagement
This prevents crashes because of mismatched versions between
logback-classic and logback-core when importing (maven's scope=import)
managed dependencies.

For exemple,
importing powsybl-core gives logback-classic 1.1.8
importing spring-dependencies gives logback-classic 1.2.3 and logback-core 1.2.3

if importing spring-dependencies first, all is well. If importing powsybl-core first,
you get the following crash:

java.lang.NoSuchMethodError: ch.qos.logback.core.util.ContextUtil.addHostNameAsProperty()V

because addHostNameAsProperty was removed in logback-core 1.2.0 and logback-classic 1.1.8 calls it
at startup in a static initializer.

Signed-off-by: Jon Harper <jon.harper87@gmail.com>